package cpu6502

type Operation func(*cpu6502) int
type Addressing func(*cpu6502) int

type Opcode struct {
	NumCycle int
	Code int
	AddressingMode int
	Op Operation
	Address Addressing
}

var Opcodes = map[uint8]Opcode{
	// ADC Opcodes (Add with Carry)
	0x69: {2, OP_ADC, ADR_IMMEDIATE, adc, immediate },
	0x65: {3, OP_ADC, ADR_ZEROPAGE, adc, zeropage  },
	0x75: {4, OP_ADC, ADR_ZEROPAGEX, adc, zeropagex },
	0x6D: {4, OP_ADC, ADR_ABSOLUTE, adc, absolute },
	0x7D: {4, OP_ADC, ADR_ABSOLUTEX, adc, absolutex },
	0x79: {4, OP_ADC, ADR_ABSOLUTEY, adc, absolutey },
	0x61: {6, OP_ADC, ADR_INDIRECTX, adc, indirectx },
	0x71: {5, OP_ADC, ADR_INDIRECTY, adc, indirecty },
	0x29: {2, OP_AND, ADR_IMMEDIATE, and, immediate },
	0x25: {3, OP_AND, ADR_ZEROPAGE, and, zeropage },
	0x35: {4, OP_AND, ADR_ZEROPAGEX, and, zeropagex },
	0x2D: {4, OP_AND, ADR_ABSOLUTE, and, absolute },
	0x3D: {4, OP_AND, ADR_ABSOLUTEX, and, absolutex },
	0x39: {4, OP_AND, ADR_ABSOLUTEY, and, absolutey },
	0x21: {6, OP_AND, ADR_INDIRECTX, and, indirectx },
	0x31: {5, OP_AND, ADR_INDIRECTY, and, indirecty },
	0x0A: {2, OP_ASL, ADR_ACCUMULATOR, asl, accumulator },
	0x06: {5, OP_ASL, ADR_ZEROPAGE, asl, zeropage },
	0x16: {6, OP_ASL, ADR_ZEROPAGEX, asl, zeropagex },
	0x0E: {6, OP_ASL, ADR_ABSOLUTE, asl, absolute },
	0x1E: {7, OP_ASL, ADR_ABSOLUTEX, asl, absolutex },
	0x24: {3, OP_BIT, ADR_ZEROPAGE, bit, zeropage },
	0x2C: {4, OP_BIT, ADR_ABSOLUTE, bit, absolute },
	0x10: {2, OP_BPL, ADR_RELATIVE, bpl, relative },  // Branch on Plus
	0x30: {2, OP_BMI, ADR_RELATIVE, bmi, relative },  // Branch on Minus
	0x50: {2, OP_BVC, ADR_RELATIVE, bvc, relative },  // Branch on Overflow Clear
	0x70: {2, OP_BVS, ADR_RELATIVE, bvs, relative },  // Branch on Overflow Set
	0x90: {2, OP_BCC, ADR_RELATIVE, bcc, relative },  // Branch on Carry Clear
	0xB0: {2, OP_BCS, ADR_RELATIVE, bcs, relative },  // Branch on Carry Set
	0xD0: {2, OP_BNE, ADR_RELATIVE, bne, relative },  // Branch on Not Equal
	0xF0: {2, OP_BEQ, ADR_RELATIVE, beq, relative },  // Branch on Equal
	0x00: {7, OP_BRK, ADR_IMPLICIT, brk, implicit },
	0xC9: {2, OP_CMP, ADR_IMMEDIATE, cmp, immediate },
	0xC5: {3, OP_CMP, ADR_ZEROPAGE, cmp, zeropage },
	0xD5: {4, OP_CMP, ADR_ZEROPAGEX, cmp, zeropagex },
	0xCD: {4, OP_CMP, ADR_ABSOLUTE, cmp, absolute },
	0xDD: {4, OP_CMP, ADR_ABSOLUTEX, cmp, absolutex },
	0xD9: {4, OP_CMP, ADR_ABSOLUTEY, cmp, absolutey },
	0xC1: {6, OP_CMP, ADR_INDIRECTX, cmp, indirectx },
	0xD1: {5, OP_CMP, ADR_INDIRECTY, cmp, indirecty },
	0xE0: {2, OP_CPX, ADR_IMMEDIATE, cpx, immediate },
	0xE4: {3, OP_CPX, ADR_ZEROPAGE, cpx, zeropage },
	0xEC: {4, OP_CPX, ADR_ABSOLUTE, cpx, absolute },
	0xC0: {2, OP_CPY, ADR_IMMEDIATE, cpy, immediate },
	0xC4: {3, OP_CPY, ADR_ZEROPAGE, cpy, zeropage },
	0xCC: {4, OP_CPY, ADR_ABSOLUTE, cpy, absolute },
	0xC6: {5, OP_DEC, ADR_ZEROPAGE, dec, zeropage },
	0xD6: {6, OP_DEC, ADR_ZEROPAGEX, dec, zeropagex },
	0xCE: {6, OP_DEC, ADR_ABSOLUTE, dec, absolute },
	0xDE: {7, OP_DEC, ADR_ABSOLUTEX, dec, absolutex },
	0x49: {2, OP_EOR, ADR_IMMEDIATE, eor, immediate },
	0x45: {3, OP_EOR, ADR_ZEROPAGE, eor, zeropage },
	0x55: {4, OP_EOR, ADR_ZEROPAGEX, eor, zeropagex },
	0x4D: {4, OP_EOR, ADR_ABSOLUTE, eor, absolute },
	0x5D: {4, OP_EOR, ADR_ABSOLUTEX, eor, absolutex },
	0x59: {4, OP_EOR, ADR_ABSOLUTEY, eor, absolutey },
	0x41: {6, OP_EOR, ADR_INDIRECTX, eor, indirectx },
	0x51: {5, OP_EOR, ADR_INDIRECTY, eor, indirecty },
	0x18: {2, OP_CLC, ADR_IMPLICIT, clc, implicit },
	0x38: {2, OP_SEC, ADR_IMPLICIT, sec, implicit },
	0x58: {2, OP_CLI, ADR_IMPLICIT, cli, implicit },
	0x78: {2, OP_SEI, ADR_IMPLICIT, sei, implicit },
	0xB8: {2, OP_CLV, ADR_IMPLICIT, clv, implicit },
	0XD8: {2, OP_CLD, ADR_IMPLICIT, cld, implicit },
	0xF8: {2, OP_SED, ADR_IMPLICIT, sed, implicit },
	0xE6: {5, OP_INC, ADR_ZEROPAGE, inc, zeropage },
	0xF6: {6, OP_INC, ADR_ZEROPAGEX, inc, zeropagex },
	0xEE: {6, OP_INC, ADR_ABSOLUTE, inc, absolute },
	0xFE: {7, OP_INC, ADR_ABSOLUTEX, inc, absolutex },
	0x4C: {3, OP_JMP, ADR_ABSOLUTE, jmp, absolute },
	0x6C: {5, OP_JMP, ADR_INDIRECT, jmp, indirect },
	0x20: {6, OP_JSR, ADR_ABSOLUTE, jsr, absolute },
	0xA9: {2, OP_LDA, ADR_IMMEDIATE, lda, immediate },
	0xA5: {3, OP_LDA, ADR_ZEROPAGE, lda, zeropage },
	0xB5: {4, OP_LDA, ADR_ZEROPAGEX, lda, zeropagex },
	0xAD: {4, OP_LDA, ADR_ABSOLUTE, lda, absolute },
	0xBD: {4, OP_LDA, ADR_ABSOLUTEX, lda, absolutex },
	0xB9: {4, OP_LDA, ADR_ABSOLUTEY, lda, absolutey },
	0xA1: {6, OP_LDA, ADR_INDIRECTX, lda, indirectx },
	0xB1: {5, OP_LDA, ADR_INDIRECTY, lda, indirecty },
	0xA2: {2, OP_LDX, ADR_IMMEDIATE, ldx, immediate },
	0xA6: {3, OP_LDX, ADR_ZEROPAGE, ldx, zeropage },
	0xB6: {4, OP_LDX, ADR_ZEROPAGEY, ldx, zeropagey },
	0xAE: {4, OP_LDX, ADR_ABSOLUTE, ldx, absolute },
	0xBE: {4, OP_LDX, ADR_ABSOLUTEY, ldx, absolutey },
	0xA0: {2, OP_LDY, ADR_IMMEDIATE, ldy, immediate },
	0xA4: {3, OP_LDY, ADR_ZEROPAGE, ldy, zeropage },
	0xB4: {4, OP_LDY, ADR_ZEROPAGEX, ldy, zeropagex },
	0xAC: {4, OP_LDY, ADR_ABSOLUTE, ldy, absolute },
	0xBC: {4, OP_LDY, ADR_ABSOLUTEX, ldy, absolutex },
	0x4A: {2, OP_LSR, ADR_ACCUMULATOR, lsr, accumulator },
	0x46: {5, OP_LSR, ADR_ZEROPAGE, lsr, zeropage },
	0x56: {6, OP_LSR, ADR_ZEROPAGEX, lsr, zeropagex },
	0x4E: {6, OP_LSR, ADR_ABSOLUTE, lsr, absolute },
	0x5E: {7, OP_LSR, ADR_ABSOLUTEX, lsr, absolutex },
	0xEA: {2, OP_NOP, ADR_IMPLICIT, nop, implicit },
	0x09: {2, OP_ORA, ADR_IMMEDIATE, ora, immediate },
	0x05: {3, OP_ORA, ADR_ZEROPAGE, ora, zeropage },
	0x15: {4, OP_ORA, ADR_ZEROPAGEX, ora, zeropagex },
	0x0D: {4, OP_ORA, ADR_ABSOLUTE, ora, absolute },
	0x1D: {4, OP_ORA, ADR_ABSOLUTEX, ora, absolutex },
	0x19: {4, OP_ORA, ADR_ABSOLUTEY, ora, absolutey },
	0x01: {6, OP_ORA, ADR_INDIRECTX, ora, indirectx },
	0x11: {5, OP_ORA, ADR_INDIRECTY, ora, indirecty },
	0xAA: {2, OP_TAX, ADR_IMPLICIT, tax, implicit },
	0x8A: {2, OP_TXA, ADR_IMPLICIT, txa, implicit },
	0xCA: {2, OP_DEX, ADR_IMPLICIT, dex, implicit },
	0xE8: {2, OP_INX, ADR_IMPLICIT, inx, implicit },
	0xA8: {2, OP_TAY, ADR_IMPLICIT, tay, implicit },
	0x98: {2, OP_TYA, ADR_IMPLICIT, tya, implicit },
	0x88: {2, OP_DEY, ADR_IMPLICIT, dey, implicit },
	0xC8: {2, OP_INY, ADR_IMPLICIT, iny, implicit },
	0x2A: {2, OP_ROL, ADR_ACCUMULATOR, rol, accumulator },
	0x26: {5, OP_ROL, ADR_ZEROPAGE, rol, zeropage },
	0x36: {6, OP_ROL, ADR_ZEROPAGEX, rol, zeropagex },
	0x2E: {6, OP_ROL, ADR_ABSOLUTE, rol, absolute },
	0x3E: {7, OP_ROL, ADR_ABSOLUTEX, rol, absolutex },
	0x6A: {2, OP_ROR, ADR_ACCUMULATOR, ror, accumulator },
	0x66: {5, OP_ROR, ADR_ZEROPAGE, ror, zeropage },
	0x76: {6, OP_ROR, ADR_ZEROPAGEX, ror, zeropagex },
	0x6E: {6, OP_ROR, ADR_ABSOLUTE, ror, absolute },
	0x7E: {7, OP_ROR, ADR_ABSOLUTEX, ror, absolutex },
	0x40: {6, OP_RTI, ADR_IMPLICIT, rti, implicit },
	0x60: {6, OP_RTS, ADR_IMPLICIT, rts, implicit },
	0xE9: {2, OP_SBC, ADR_IMMEDIATE, sbc, immediate },
	0xE5: {3, OP_SBC, ADR_ZEROPAGE, sbc, zeropage },
	0xF5: {4, OP_SBC, ADR_ZEROPAGEX, sbc, zeropagex },
	0xED: {4, OP_SBC, ADR_ABSOLUTE, sbc, absolute },
	0xFD: {4, OP_SBC, ADR_ABSOLUTEX, sbc, absolutex },
	0xF9: {4, OP_SBC, ADR_ABSOLUTEY, sbc, absolutey },
	0xE1: {6, OP_SBC, ADR_INDIRECTX, sbc, indirectx },
	0xF1: {5, OP_SBC, ADR_INDIRECTY, sbc, indirecty },
	0x85: {3, OP_STA, ADR_ZEROPAGE, sta, zeropage },
	0x95: {4, OP_STA, ADR_ZEROPAGEX, sta, zeropagex },
	0x8D: {4, OP_STA, ADR_ABSOLUTE, sta, absolute },
	0x9D: {5, OP_STA, ADR_ABSOLUTEX, sta, absolutex },
	0x99: {5, OP_STA, ADR_ABSOLUTEY, sta, absolutey },
	0x81: {6, OP_STA, ADR_INDIRECTX, sta, indirectx },
	0x91: {6, OP_STA, ADR_INDIRECTY, sta, indirecty },
	0x9A: {2, OP_TXS, ADR_IMPLICIT, txs, implicit },
	0xBA: {2, OP_TSX, ADR_IMPLICIT, tsx, implicit },
	0x48: {3, OP_PHA, ADR_IMPLICIT, pha, implicit },
	0x68: {4, OP_PLA, ADR_IMPLICIT, pla, implicit },
	0x08: {3, OP_PHP, ADR_IMPLICIT, php, implicit },
	0x28: {4, OP_PLP, ADR_IMPLICIT, plp, implicit },
	0x86: {3, OP_STX, ADR_ZEROPAGE, stx, zeropage },
	0x96: {4, OP_STX, ADR_ZEROPAGEY, stx, zeropagey },
	0x8E: {4, OP_STX, ADR_ABSOLUTE, stx, absolute },
	0x84: {3, OP_STY, ADR_ZEROPAGE, sty, zeropage },
	0x94: {4, OP_STY, ADR_ZEROPAGEX, sty, zeropagex },
	0x8C: {4, OP_STY, ADR_ABSOLUTE, sty, absolute },
}